"""add read

Revision ID: 0f6233efdc6d
Revises: 2c98034d4fac
Create Date: 2025-04-24 14:53:31.078009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6233efdc6d'
down_revision: Union[str, None] = '2c98034d4fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('students', sa.Column('is_read', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'is_read')
    op.drop_column('employees', 'is_read')
    # ### end Alembic commands ###
