"""add username

Revision ID: 1de317c6e36c
Revises: f9bb1ff67947
Create Date: 2025-04-27 12:06:30.148363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de317c6e36c'
down_revision: Union[str, None] = 'f9bb1ff67947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('image_path', sa.String(), nullable=True),
        sa.Column('body', sa.String(), nullable=False),
        sa.Column('date', sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('blog_id', sa.Integer(), nullable=True),
        sa.Column('image_path', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('students', sa.Column('username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'username')
    op.drop_table('blog_images')
    op.drop_table('blogs')
    # ### end Alembic commands ###