"""Add phone_number in employe

Revision ID: 2c98034d4fac
Revises: 2b0c8aff1859
Create Date: 2025-04-24 14:25:52.885094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c98034d4fac'
down_revision: Union[str, None] = '2b0c8aff1859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'phone_number')
    # ### end Alembic commands ###
