"""Add about username

Revision ID: 872c46a53d25
Revises: 1de317c6e36c
Create Date: 2025-04-27 12:31:08.615951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872c46a53d25'
down_revision: Union[str, None] = '1de317c6e36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('students', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('students', sa.Column('father_name', sa.String(), nullable=False))
    op.add_column('students', sa.Column('direction', sa.String(), nullable=False))
    op.drop_column('students', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('students', 'direction')
    op.drop_column('students', 'father_name')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'first_name')
    # ### end Alembic commands ###
