"""Delete image path

Revision ID: 93358eed712d
Revises: 872c46a53d25
Create Date: 2025-04-27 13:14:56.282613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93358eed712d'
down_revision: Union[str, None] = '872c46a53d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
