"""first name

Revision ID: 9a1d546a8f65
Revises: 3ea8362eac82
Create Date: 2025-04-30 15:26:02.629999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a1d546a8f65'
down_revision: Union[str, None] = '3ea8362eac82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'father_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('father_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
